In [63]:
# student no:98170668
# Name:sara azarnoush

#please name your file as
# HW5_StudentNo_StudentName.ipynb

import numpy as np
import scipy as sp
import scipy.linalg as linalg

#do not add any other imports here

In [64]:
matrix1 = np.array([[1,3,5],[0,3,9],[10,4,9]])

## QR Decomposition
Decompose the matrix using QR decomposition and reconstruct it afterwards (using python libraries)

In [65]:
Q, R = np.linalg.qr(matrix1)
reconstructed1 = np.matmul(Q, R)
print(reconstructed1)

[[ 1.  3.  5.]
 [ 0.  3.  9.]
 [10.  4.  9.]]


## Classical Gram-Schmidt for QR decomposition

Implement classical Gram Schmidt for QR decomposition ( you can not directly call python functions for QR decomposition )

In [66]:
def cgs(A):
    m = A.shape[0]
    n = A.shape[1]
    Q = np.zeros([m, m])
    R = np.zeros([m, n])
    AC1 = A[:, 0]
    R[0, 0] = np.linalg.norm(AC1)
    R0 = R[0, 0]
    if R0 != 0:
        Q[:, 0] = AC1/R0
    for i in range(n-1):
        Q[:, i+1] = A[:, i+1]
        for j in range(i+1):
            R[j, i+1] = np.dot(Q[:, j].T, Q[:, i+1])
            Q[:, i+1] -= R[j, i+1]*Q[:, j]
        R[i+1, i+1] = np.linalg.norm(Q[:, i+1])
        if R[i+1, i+1] != 0:
            Q[:, i+1] /= R[i+1, i+1]
    return Q, R


In [67]:
Q,R = cgs(matrix1)
reconstructed2 = np.matmul(Q, R)
np.allclose(reconstructed1,reconstructed2)

True

## LU Decomposition

Decompose the matrix using LU decomposition and reconstruct it afterwards (using python libraries)

In [68]:
P,L,U = sp.linalg.lu(matrix1)
reconstructed = np.matmul(P, np.matmul(L, U))
print(reconstructed)

[[ 1.  3.  5.]
 [ 0.  3.  9.]
 [10.  4.  9.]]


## Eigen Decomposition

Use python libraries to get eigen values and eigen vectors

In [69]:
values, vectors = np.linalg.eig(matrix1)
print(values)
print(vectors)

[16.30098987+0.j         -1.65049493+2.02120481j -1.65049493-2.02120481j]
[[ 0.35564109+0.j          0.0872543 -0.28570889j  0.0872543 +0.28570889j]
 [ 0.52376849+0.j          0.83145052+0.j          0.83145052-0.j        ]
 [ 0.77407104+0.j         -0.42962849+0.18672575j -0.42962849-0.18672575j]]


Now reconstruct the matrix using values which you dervied before

In [70]:
# factorize
values, vectors = np.linalg.eig(matrix1)
# create matrix from eigenvectors
Q = vectors
# create inverse of eigenvectors matrix
R = np.linalg.inv(vectors)
# create diagonal matrix from eigenvalues
L = np.diag(values)
# reconstruct the original matrix
B = np.matmul(Q, np.matmul(L, R))
print(np.round(B))

[[ 1.+0.j  3.-0.j  5.-0.j]
 [-0.+0.j  3.+0.j  9.-0.j]
 [10.+0.j  4.+0.j  9.-0.j]]


Now, Can you get the matrix inverse via eigenvector and eigenvalues?


In [71]:
matrix_inverse_using_scipy = sp.linalg.inv(matrix1)
matrix_inverse_using_eigen_decomposition = np.matmul(Q, np.matmul(np.diag(1 / values), R))

np.allclose(matrix_inverse_using_scipy, matrix_inverse_using_eigen_decomposition)

True

## SVD 

Get SVD via python functions and recontruct it to check it is close to the real one

In [72]:
U, s, VT = np.linalg.svd(matrix1)
np.allclose(matrix1, np.matmul(U, np.matmul(np.diag(s), VT)))

True